### ISSUE TITLE
MacOS X issue

### ISSUE THREAD

**Issue by yoglo** [althonos/mzml2isa#12]
The latest version doesn't run on MacOS X (Version 10.11.3), both with python2.7 and python3.5.

command: 
```
python -m mzml2isa.mzml A1.mzML
```
Error log:

```python
Traceback (most recent call last):
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/mzml2isa/mzml.py", line 105, in __init__
    self.obo = Ontology('https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo', False)
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/ontology.py", line 103, in __init__
    self.parse(handle)
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/ontology.py", line 164, in parse
    self.meta, self.terms, self.imports = parser.parse(stream)
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/parser/__init__.py", line 35, in parse
    self.makeTree()
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/parser/obo.py", line 194, in makeTree
    while self._terms.qsize() > 0 or self._rawterms.qsize() > 0:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/mzml2isa/mzml.py", line 1008, in <module>
    print(mzMLmeta(sys.argv[-1]).meta_json)
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/mzml2isa/mzml.py", line 109, in __init__
    "psi-ms.obo"))
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/ontology.py", line 103, in __init__
    self.parse(handle)
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/ontology.py", line 164, in parse
    self.meta, self.terms, self.imports = parser.parse(stream)
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/parser/__init__.py", line 35, in parse
    self.makeTree()
  File "/Users/yoanngloaguen/Documents/isaTabTest/venv3/lib/python3.5/site-packages/pronto/parser/obo.py", line 194, in makeTree
    while self._terms.qsize() > 0 or self._rawterms.qsize() > 0:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

**Comment by althonos** [comment]
This is a Python stdlib issue, seems multiprocessing relies on a Semaphore API not provided by Mac.
I'll try to find a way to change the code to avoid that, although it has to do with https://github.com/althonos/pronto which mzml2isa uses to parse the ontology file.

**Comment by althonos** [comment]
This issue was hopefully fixed with version 0.3.3 of pronto, so if you just run an update with pip ( `pip install mzml2isa -U` ) it should work.
I have no way of testing it on OS X however so would you mind telling me if this works now?

**Comment by yoglo** [comment]
Yes, this is now working, thank you for fixing it that quickly.

**Comment by althonos** [comment]
Thanks !
